create database vendas;

use vendas;

CREATE TABLE IF NOT EXISTS USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);

INSERT INTO USUARIOS(LOGIN, SENHA, ADMIN) VALUES
('testeSinerji', '$2a$10$q8G.P5PB0y4HrZSt4pfbueau/VU/.3jcHUoTRHiAFhOQi/zRRy0I2', FALSE),
('testeAdmin', '$2a$10$5kHXR6sK5w8G65u3CcBqwOvIWykigRZMmF7q2HjrVY/tNAe4uBRoy', TRUE);